---
- name: List available PowerVC Images
  hosts: localhost
  tasks:
    - name: Retrieve list of all AIX images
      openstack.cloud.image_info:
      register: result

    - name: Print image list
      debug:
        msg: "{{ result.openstack_image }}"
