--- 
- 
  gather_facts: false
  hosts: all
  name: power
  tasks: 
    - 
      name: "Retrieve list of all AIX images"
      openstack.cloud.os_image_info: 
        properties: ~
      register: result
    - 
      debug: 
        msg: "{{ result | json_query('openstack_image[*]. {name: name, id: id, os_distro: os_distro, status: status, project: location.project.name}') }}"
      name: "Print image list"
